### ISSUE TITLE
"write text on top of the background image"

### ISSUE THREAD

**Issue by texadactyl** [gutschke/pdf2odt#8]
[lecture.02.pdf](https://github.com/gutschke/pdf2odt/files/1812639/lecture.02.pdf)

I successfully converted the attached "lecture.02.pdf" to an ODT.  I can launch the ODT with LibreOffice Writer.  But, I cannot write where I want to over the background image.

For example, there is a statement beginning with "cathode rays = _______" on the first page.  I would like to write "negatively" over the underscores.

- Down and right arrow takes me to the top margin of the next page.
- Up and left arrow takes me to the top margin of the previous page.
- Clicking anywhere on the background image takes me to the top margin of the current page.

What am I missing?  Perhaps, the README.md needs some explanation about how to use the ODT in LibreOffice? (E.g. special configuration setting in Writer)

LibreOffice version: Version: 5.4.5.1
Build ID: 1:5.4.5-0ubuntu0.17.10.5
CPU threads: 2; OS: Linux 4.13; UI render: default; VCL: gtk3; 
Locale: en-US (en_US.UTF-8); Calc: group

**Comment by gutschke** [comment]
There are three different ways that people usually go about using pdf2odt.

1. You can convert PDF files to ODT text documents. By adjusting
paragraph/line spacing and tabulator positions, the cursor can be placed
anywhere in the page and text can be typed on top of the background image
(i.e. the original document). Please note that you can only place the
cursor where there is leading white space. So, if you haven't entered any
spaces or newlines, you are restricted to the top of the page. Don't
introduce any page breaks, unless you plan on duplicating a page. There is
some amount of "snapping" that LibreOffice Writer performs. So, alignment
cannot be arbitrarily precise. But that rarely matters in practice. It is
difficult to white-out any existing text with this method. That's simply
not anything that Writer naturally does. I think the only solution is
overlaying a white JPEG image on top of text that you want to disappear.
It's cumbersome, but doable.

2. You can convert PDF files to ODS spreadsheets. These files have lots of
tiny little cells. You can select a rectangular region of cells and merge
them into one big cell. This new cell then allows you to enter text. In
general, you have similar constraints to what I mentioned earlier, though.
I personally find that ODT documents are easier to edit, but some users
prefer ODS.

3. For complex operations, and if you do need to white out a lot of the
original input files, neither option works great. Instead, you should
convert to ODT and then use "unzip" to unpack the ODT file. You'll find a
folder with all of the background images that form the original document.
Edit these files in an image editor (e.g. Gimp). When you are done, use
pdf2odt to convert the image files to an ODT document. You can simply list
all of the image files as inputs (instead of listing a PDF input file).

**Comment by texadactyl** [comment]
As I said initially, I converted the supplied PDF to ODT (your #1 case above).  The README .md states that I can simply write on top of the background image wherever I wish.  This is apparently not the case.

Have you tried the attachment I supplied?  What did you do to gain the ability to simply write on top of the background image at the location that I described?

**Comment by gutschke** [comment]
Did you read what I said about whitespace? pdf2odt doesn't magically change how LibreOffice works. It simply gives you a document with lots of "blank" pages. But each of these blank pages has a background image. Other than this small adjustment to the page styles, LibreOffice Writer is pretty much oblivious to the fact that you can see something other than a blank piece of paper.

You can write just the same way how you would always write in LibreOffice Writer. You start at the top of the page and as you keep writing, you add more white space and more text to the page. Everything that you write is printed on top of the background image, which acts a little similar to a "watermark".

Think of it the same way how you would fill out a document with an old-school typewriter. You take the original document and load it into your type writer. You then keep typing SPC or ENTER until the paper is positioned the way you want it. Then you enter text.

You could do the same with a modern printer. Take the original document and load it into the paper cassette. Then print another document on top of it. This second document would mostly contain blank space, and only a small number of lines that have text.
